### ISSUE TITLE
Local Environment

### ISSUE THREAD

**Issue by bennettapps** [bennettapps/Budget-App#1]
Setup local environment and Sync to this Cloud Repository.

**Comment by Rezokeun** [comment]
Great job on getting started. Keep on going!

**Comment by bennettapps** [comment]
I'm having a bit of trouble with this. I created a simple Android Studio project and committed it, but I don't think it's set up quite right: my project is a folder within the repo. You can see it right now. I can't just open the repo in Android Studio, I have to open the subfolder. Is this right? Or is there a better way?

**Comment by Rezokeun** [comment]
You're right in that you should be able to have your repo be the primary folder. Have you tried this? https://stackoverflow.com/questions/37093723/how-to-add-an-android-studio-project-to-github

Here's an example of an android app using a repo as the top folder of the hierarchy - https://github.com/zom/Zom-Android-XMPP

**Comment by Rezokeun** [comment]
Also, if it's easier, don't feel bad about blowing away your repo and starting over. I'd rather you save time and learn than spend too much time troubleshooting git. You only need to know enough git to get your workflow down, otherwise coding is where you want to build skill in not git. So only do what you need to get this going. Once you have your dev workflow down and basic commands shift 100% to learning Kotlin.
